# RBS Pools Schema in dev environment
---
poolConfigs:
  - poolId: "aou_ws_test_v1"
    size: 10
    resourceConfigName: "aou_ws_resource_test_v1"
  - poolId: "cwb_ws_dev_v1"
    size: 10
    resourceConfigName: "cwb_ws_resource_dev_v1"
