# Resource Buffer Service Pools Schema in dev environment
---
poolConfigs:
  - poolId: "cwb_ws_dev_v2"
    size: 300
    resourceConfigName: "cwb_ws_resource_dev_v2"
  - poolId: "workspace_manager_v6"
    size: 300
    resourceConfigName: "workspace_manager_v6"
  - poolId: "vpc_sc_v1"
    size: 300
    resourceConfigName: "vpc_sc_v1"
  - poolId: "datarepo_v1"
    size: 300
    resourceConfigName: datarepo_v1"

