# Community Workbench buffered workspace template
---
configName: "vpc_sc_v1"
gcpProjectConfig:
  projectIdSchema:
    prefix: "terra-vpc-sc-alpha"
    scheme: "RANDOM_CHAR"
  # test.firecloud.org/alpha/for_vpc_sc_unclaimed
  parentFolderId: "38455243798"
  billingAccount: "01A82E-CA8A14-367457"
  enabledApis:
  - "bigquery-json.googleapis.com"
  - "compute.googleapis.com"
  - "container.googleapis.com"
  - "containerregistry.googleapis.com"
  - "cloudbilling.googleapis.com"
  - "clouderrorreporting.googleapis.com"
  - "cloudkms.googleapis.com"
  - "cloudtrace.googleapis.com"
  - "dataflow.googleapis.com"
  - "dataproc.googleapis.com"
  - "dns.googleapis.com"
  - "genomics.googleapis.com"
  - "lifesciences.googleapis.com"
  - "logging.googleapis.com"
  - "monitoring.googleapis.com"
  - "storage-api.googleapis.com"
  - "storage-component.googleapis.com"
  network:
    enableNetworkMonitoring: "true"
