# RBS Pools Schema for running buffer service integration test and performace test.
---
poolConfigs:
  - poolId: "resource_buffer_test_v3"
    size: 1500
    resourceConfigName: "resource_buffer_test_v3"
