# RBS Pools Schema in tools environment
---
poolConfigs:
  - poolId: "cwb_ws_fiab_v1"
    size: 50
    resourceConfigName: "cwb_ws_resource_fiab_v1"
  - poolId: "workspace_manager_v1"
    size: 50
    resourceConfigName: "workspace_manager_v1"
