# RBS Pools Schema in tools environment
---
poolConfigs:
  - poolId: "cwb_ws_fiab_v2"
    size: 500
    resourceConfigName: "cwb_ws_resource_fiab_v2"
  - poolId: "cwb_ws_quality_v2"
    size: 500
    resourceConfigName: "cwb_ws_resource_quality_v2"
  - poolId: "workspace_manager_v6"
    size: 500
    resourceConfigName: "workspace_manager_v6"
  - poolId: "datarepo_v1"
    size: 300
    resourceConfigName: "datarepo_v1"
