# All Of Us buffered workspace template
---
configName: "aou_ws_resource_v1"
gcpProjectConfig:
  projectIdSchema:
    prefix: "aou-rw-test"
    scheme: "RANDOM_CHAR"
  # test.firecloud.org/terra_dev_aou_test
  parentFolderId: "737976594150"
  billingAccount: "01A82E-CA8A14-367457"
  enabledApis:
    - "bigquery-json.googleapis.com"
    - "compute.googleapis.com"
    - "container.googleapis.com"
    - "cloudbilling.googleapis.com"
    - "clouderrorreporting.googleapis.com"
    - "cloudkms.googleapis.com"
    - "cloudtrace.googleapis.com"
    - "containerregistry.googleapis.com"
    - "dataflow.googleapis.com"
    - "dataproc.googleapis.com"
    - "genomics.googleapis.com"
    - "logging.googleapis.com"
    - "monitoring.googleapis.com"
    - "storage-api.googleapis.com"
    - "storage-component.googleapis.com"
    - "dns.googleapis.com"
  iamBindings:
    - members: ["group:firecloud-project-owners@test.firecloud.org"]
      role: "roles/owner"
    - members: ["serviceAccount:806222273987-gffklo3qfd1gedvlgr55i84cocjh8efa@developer.gserviceaccount.com", "serviceAccount:806222273987-ksinuueghug8u81i36lq8aof266q19hl@developer.gserviceaccount.com"]
      role: "roles/editor"
  network:
    enableNetworkMonitoring: "true"