# Resource template for local testing and personal environment on GKE
---
configName: "ws_resource_toolsalpha_v1"
gcpProjectConfig:
  projectIdSchema:
    prefix: "terra-toolsalpha"
    scheme: "RANDOM_CHAR"
  # RBS Testing
  parentFolderId: "637867149294"
  billingAccount: "01A82E-CA8A14-367457"
  enabledApis:
    - "bigquery-json.googleapis.com"
    - "compute.googleapis.com"
    - "container.googleapis.com"
    - "cloudbilling.googleapis.com"
    - "clouderrorreporting.googleapis.com"
    - "cloudkms.googleapis.com"
    - "cloudtrace.googleapis.com"
    - "containerregistry.googleapis.com"
    - "dataflow.googleapis.com"
    - "dataproc.googleapis.com"
    - "genomics.googleapis.com"
    - "logging.googleapis.com"
    - "monitoring.googleapis.com"
    - "storage-api.googleapis.com"
    - "storage-component.googleapis.com"
    - "dns.googleapis.com"
  iamBindings:
    - members: ["group:terra-rbs-test@broadinstitute.org"]
      role: "roles/editor"
    - members: ["terra-rbs-viewer-test@broadinstitute.org"]
      role: "roles/viewer"
  network:
    enableNetworkMonitoring: "true"