# Community Workbench buffered workspace template
---
configName: "cwb_ws_resource_perf_v1"
gcpProjectConfig:
  projectIdSchema:
    prefix: "terra-perf"
    scheme: "RANDOM_CHAR"
  # qulity.firecloud.org/quality/CommunityWorkbench
  parentFolderId: "180789000311"
  billingAccount: "01A82E-CA8A14-367457"
  enabledApis:
  - "bigquery-json.googleapis.com"
  - "compute.googleapis.com"
  - "container.googleapis.com"
  - "containerregistry.googleapis.com"
  - "cloudbilling.googleapis.com"
  - "clouderrorreporting.googleapis.com"
  - "cloudkms.googleapis.com"
  - "cloudtrace.googleapis.com"
  - "dataflow.googleapis.com"
  - "dataproc.googleapis.com"
  - "dns.googleapis.com"
  - "genomics.googleapis.com"
  - "lifesciences.googleapis.com"
  - "logging.googleapis.com"
  - "monitoring.googleapis.com"
  - "notebooks.googleapis.com"
  - "storage-api.googleapis.com"
  - "storage-component.googleapis.com"
  network:
    enableNetworkMonitoring: "false"
