openapi: 3.0.0
info:
  title: Terra Resource Buffer Service API
  description: |
    Resource Buffering Service to allocate and buffer cloud resources
  version: 0.0.1

servers:
  - url: /

security:
  - bearerAuth: []
  - authorization: [openid, email, profile]

paths:
  '/status':
    get:
      security: []
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
        - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

  '/api/pool/v1/{poolId}/resource':
    put:
      summary: Get a resource from pool and update the resource state, each handoutRequestId is assigned to the resource no more than once. Using the same handoutRequestId will get the same ResourceInfo
      operationId: handoutResource
      parameters:
        - $ref: '#/components/parameters/PoolId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/parameters/HandoutRequestId'
      tags:
        - buffer
      responses:
        '200':
          description: OK, using the same handoutRequestId will also get 200 back with the same ResourceInfo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceInfo'
        '404':
          description: No resource available in this pool.
        '500':
          description: Get request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'

  '/api/pool/v1/{poolId}':
    get:
      summary: Get the pool info, including resource count in each state, and pool config.
      operationId: getPoolInfo
      parameters:
        - $ref: '#/components/parameters/PoolId'
      tags:
        - buffer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolInfo'
        '404':
          description: No resource available in this pool.
        '500':
          description: Get request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'

components:
  parameters:
    PoolId:
      name: poolId
      in: path
      description: |-
        Unique identity of a pool
      required: true
      schema:
        type: string

  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    HandoutRequestId:
      description: |-
        The unique identifier presented by the client for a resource request.
        Using the same handoutRequestId in the same pool would ge the same resource back.
      type: string

    PoolConfigs:
      description: |-
        Terra Resource Buffer Service Reource Pools
      required:
        - poolConfigs
      properties:
        poolConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PoolConfig'
      type: object

    PoolConfig:
      description: |-
        Terra Resource Buffer Service Reource Pool Config
      required:
        - poolId
        - size
        - resourceConfigName
      properties:
        poolId:
          description: |
            A unique id for the pool. No two pools can ever have the same id. Any string is allowed.
          type: string
        size:
          description: |
            Maximum number of resources in the pool.
          type: integer
        resourceConfigName:
          description: |
            The config name the pool use. Resource Buffer Service will use it to locate the actual config file.
          type: string
      type: object

    ResourceInfo:
      description: |-
        Information represents a resource in Resource Buffer Service
      required:
        - poolId
        - requestHandoutId
        - cloudResourceUid
      properties:
        poolId:
          description: |
            The pool id the resource belongs to.
          type: string
        requestHandoutId:
          description: |
            The unique identifier used for handout resource. Resource Buffer Service will handout the same resource for the same id.
          type: string
        cloudResourceUid:
          $ref: '../../../../build/crlSchema/cloud_resources_uid.yaml#/components/schemas/CloudResourceUid'
      type: object

    PoolInfo:
      description: |-
        Information represents a pool in Resource Buffer Service
      required:
        - poolId
        - status
      properties:
        poolConfig:
          $ref: '#/components/schemas/PoolConfig'
        status:
          $ref: '#/components/schemas/PoolStatus'
        resourceStateCount:
          description: |
            Number of resources in each state
          type: object
          additionalProperties:
            type: integer
      type: object

    PoolStatus:
      type: string
      description: Possible pool status.
      enum:
        - ACTIVE
        - DEACTIVATED

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    authorization:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            openid: open id authorization
            email: email authorization
            profile: profile authorization
