openapi: 3.0.0
info:
  title: RBS API
  description: |
    Resource Buffering Service to allocate and buffer cloud resources
  version: 0.0.1

servers:
  - url: /

paths:
  '/status':
    get:
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
        - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

  '/api/pool/v1/{poolId}/resource/{handoutRequestId}':
    put:
      summary: Get a resource from pool and update the resource state, each handoutRequestId is assigned to the resource no more than once. Using the same handoutRequestId will get the same ResourceInfo
      operationId: handoutResource
      parameters:
        - $ref: '#/components/parameters/PoolId'
        - $ref: '#/components/parameters/HandoutRequestId'
      tags:
        - rbs
      responses:
        '200':
          description: OK, using the same handoutRequestId will also get 200 back with the same ResourceInfo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceInfo'
        '404':
          description: No resource available in this pool.
        '500':
          description: Get request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorReport'
components:
  parameters:
    PoolId:
      name: poolId
      in: path
      description: |-
        Unique identity of a pool
      required: true
      schema:
        type: string

    HandoutRequestId:
      name: handoutRequestId
      in: path
      description: |-
        The unique identifier presented by the client for a resource request.
        Using the same handoutRequestId in the same pool would ge the same resource back.
      required: true
      schema:
        type: string

  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    PoolConfigs:
      description: |-
        Terra RBS Reource Pools
      required:
        - poolConfigs
      properties:
        poolConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PoolConfig'
      type: object

    PoolConfig:
      description: |-
        Terra RBS Reource Pool Config
      required:
        - poolId
        - size
        - resourceConfigName
      properties:
        poolId:
          description: |
            A unique id for the pool. No two pools can ever have the same id. Any string is allowed.
          type: string
        size:
          description: |
            Maximum number of resources in the pool.
          type: integer
        resourceConfigName:
          description: |
            The config name the pool use. RBS will use it to locate the actual config file.
          type: string
      type: object

    ResourceInfo:
      description: |-
        Information represents a resource in RBS
      required:
        - poolId
        - requestHandoutId
        - cloudResourceUid
      properties:
        poolId:
          description: |
            The pool id the resource belongs to.
          type: string
        requestHandoutId:
          description: |
            The unique identifier used for handout resource. RBS will handout the same resource for the same id.
          type: string
        cloudResourceUid:
          $ref: '../../../../build/crlSchema/cloud_resources_uid.yaml#/components/schemas/CloudResourceUid'
      type: object

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'
