openapi: 3.0.0
info:
  title: RBS API
  description: |
    Resource Buffering Service to allocate and buffer cloud resources
  version: 0.0.1

servers:
  - url: /

paths:
  '/status':
    get:
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
        - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

  '/api/rbs/v1/ping':
    post:
      description: |
        Send a message and get it back in the response
      operationId: ping
      tags:
        - rbs
      parameters:
        - in: query
          name: message
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
        500:
          $ref: '#/components/responses/ErrorResponse'

components:
  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    Pools:
      description: |-
        Terra RBS Reource Pools
      required:
        - poolConfigs
      properties:
        poolConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PoolConfig'
      type: object

    PoolConfig:
      description: |-
        Terra RBS Reource Pool Config
      required:
        - poolName
        - version
        - size
        - resourceConfigName
      properties:
        resourceConfigName:
          type: string
        version:
          type: string
        size:
          type: integer
      type: object

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'


