openapi: 3.0.0
info:
  title: RBS API
  description: |
    Resource Buffering Service to allocate and buffer cloud resources
  version: 0.0.1

servers:
  - url: /

paths:
  '/status':
    get:
      description: |
        Returns the operational status of the service
      operationId: serviceStatus
      tags:
        - unauthenticated
      responses:
        200:
          description: Service is functional
          $ref: '#/components/responses/StatusResponse'
        500:
          description: Service is broken
          $ref: '#/components/responses/StatusResponse'

components:
  schemas:
    ErrorReport:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: integer
        causes:
          type: array
          items:
            type: string

    SystemStatus:
      type: object
      properties:
        ok:
          type: boolean
          description: status of this service
        systems:
          type: object
          additionalProperties:
            type: object
            properties:
              ok:
                type: boolean
              messages:
                type: array
                items:
                  type: string

    PoolConfigs:
      description: |-
        Terra RBS Reource Pools
      required:
        - poolConfigs
      properties:
        poolConfigs:
          type: array
          items:
            $ref: '#/components/schemas/PoolConfig'
      type: object

    PoolConfig:
      description: |-
        Terra RBS Reource Pool Config
      required:
        - poolId
        - size
        - resourceConfigName
      properties:
        poolId:
          description: |
            A unique id for the pool. No two pools can ever have the same id. Any string is allowed.
          type: string
        size:
          description: |
            Maximum number of resources in the pool.
          type: integer
        resourceConfigName:
          description: |
            The config name the pool use. RBS will use it to locate the actual config file.
          type: string
      type: object

    PoolConfig:
      description: |-
        Terra RBS Reource Pool Config
      required:
        - poolId
        - size
        - resourceConfigName
      properties:
        poolId:
          description: |
            A unique id for the pool. No two pools can ever have the same id. Any string is allowed.
          type: string
        size:
          description: |
            Maximum number of resources in the pool.
          type: integer
        resourceConfigName:
          description: |
            The config name the pool use. RBS will use it to locate the actual config file.
          type: string
      type: object

    CloudResourceUid:
      $ref: '../../../../build/crlSchema/cloud_resources_uid.yaml#/components/schemas/CloudResourceUid'

    ResourceInfo:
      description: |-
        Information represents a resource in RBS
      required:
        - poolId
        - size
        - resourceConfigName
      properties:
        poolId:
          description: |
            A unique id for the pool. No two pools can ever have the same id. Any string is allowed.
          type: string
        size:
          description: |
            Maximum number of resources in the pool.
          type: integer
        resourceConfigName:
          description: |
            The config name the pool use. RBS will use it to locate the actual config file.
          type: string
      type: object

  responses:
    ErrorResponse:
      description: common error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorReport'

    StatusResponse:
      description: common status response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SystemStatus'


